# Generated by Django 4.2.13 on 2024-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
