# Generated by Django 4.2.11 on 2024-04-13 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResetPasswordCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('is_confirmation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
